version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "torch"
        versions: ["< 2.3.1"]
      - dependency-name: "python-jose"
        versions: ["< 3.3.2"] 
      - dependency-name: "cryptography"
        versions: ["< 42.0.5"]

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "torch"
        versions: ["< 2.3.1"]
      - dependency-name: "python-jose"
        versions: ["< 3.3.2"]
