# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"  # For Python dependencies
    directory: "/"  # Looks for requirements.txt in root
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "mechmind-dwv"
    commit-message:
      prefix: "chore"
      prefix-development: "chore-dev"
      interval: "daily"
    ignore:
      - dependency-name: "torch"
        versions: ["< 2.3.1"]
      - dependency-name: "python-jose"
        versions: ["< 3.3.2"] 
      - dependency-name: "cryptography"
        versions: ["< 42.0.5"]

  - package-ecosystem: "github-actions"  # For GitHub Actions
    directory: "/.github/workflows"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"  # If you have JavaScript/Node.js dependencies
    directory: "/"  # Looks for package.json
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
      interval: "daily"
    ignore:
      - dependency-name: "torch"
        versions: ["< 2.3.1"]
      - dependency-name: "python-jose"
        versions: ["< 3.3.2"]
