# .github/workflows/validate-templates.yml
name: Validación
on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Validación Estructural
        run: |
          pip install yamllint jinja2-cli
          yamllint variables/
          for file in templates/*/*.j2; do
            jinja2-cli --format=json $file variables/globales.yaml > /dev/null
          done
