quality-assurance:
    runs-on: ubuntu-latest
    needs: validate-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Code formatting check (Black)
        run: black --check backend/

      - name: Run static type checking
        run: |
          pip install mypy
          mypy --ignore-missing-imports backend/
