name: Validaci칩n YAML
on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para obtener todo el historial de commits
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # Habilita cache autom치tico para pip
          
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cache/pip
            ~/.local/bin
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pyyaml>=6.0 pathspec>=0.12 MarkupSafe>=2.0 yamllint>=1.37 jinja2>=3.1 jinja2-cli>=0.8
          echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH
          
      - name: Validate YAML files
        run: |
          echo "::group::System Information"
          python --version
          pip list
          echo "::endgroup::"
          
          echo "::group::Validating YAML files"
          # Validaci칩n estructural con yamllint
          find . -name "*.yaml" -o -name "*.yml" | xargs -I {} sh -c 'echo "Validating {}"; python -m yamllint {}'
          
          # Validaci칩n de templates Jinja2
          for file in $(find . -name "*.yaml" -o -name "*.yml"); do
            echo "Checking Jinja2 templates in $file"
            if ! python -m jinja2cli "$file" > /dev/null 2>&1; then
              echo "::error file=$file::Jinja2 template validation failed"
              exit 1
            fi
          done
          echo "::endgroup::"
          
          echo "::notice::All YAML files validated successfully"
          
      - name: Upload validation report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: yaml-validation-report
          path: |
            yamllint.log
          retention-days: 3
