name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pytest pytest-django pytest-cov
        pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files

    - name: Run tests
      run: |
        cd backend
        export DJANGO_SETTINGS_MODULE=config.settings
        python -m pytest tests/ -v --cov=backend --cov-report=xml
        python manage.py test

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
