name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r tools/requirements.txt
        pip install pytest pytest-django pytest-cov safety bandit

    - name: Security checks
      run: |
        echo "=== Safety Check ==="
        safety scan --full-report
        echo "=== Bandit Analysis ==="
        bandit -r backend -ll

    - name: Run tests
      run: |
        cd backend
        export DJANGO_SETTINGS_MODULE=config.settings
        python manage.py migrate
        python manage.py test
        pytest tests/ -v --cov=config --cov-report=term-missing
