name: Despliegue Continuo

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'deploy/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Docker
      uses: docker/setup-buildx-action@v2

    - name: Login a Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Desplegar en Producción
      run: |
        cd deploy/scripts
        chmod +x deploy.sh
        ./deploy.sh production ${{ github.sha }}
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
