name: Python CI (MechBot Templates)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt  # Ruta corregida
          pip install jinja2 pyyaml  # Librerías adicionales

      - name: Validate YAML variables
        run: |
          python -c "import yaml; yaml.safe_load(open('variables_globales.yaml'))"
          echo "✅ YAML válido"

      - name: Check folder structure
        run: |
          [ -d "herramientas" ] || exit 1
          [ -f "variables_globales.yaml" ] || exit 1
          [ -f "backend/requirements.txt" ] || exit 1

      - name: Test template generation
        run: |
          cd herramientas/
          python generador.py -t comunicacion/onboarding

      - name: Test template rendering
        run: |
          python -c "from jinja2 import Environment, FileSystemLoader; env = Environment(loader=FileSystemLoader('comunicacion/')); template = env.get_template('onboarding.html'); print(template.render())"
