jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10] # Ensure valid versions are listed
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
        [![.github/workflows/django.yml](https://github.com/mechmind-dwv/mechbot-templates/actions/workflows/django.yml/badge.svg)](https://github.com/mechmind-dwv/mechbot-templates/actions/workflows/django.yml)
