name: Python CI (MechBot Templates)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install jinja2 pyyaml  # Librerías clave para plantillas

      - name: Validate YAML variables
        run: |
          python -c "import yaml; yaml.safe_load(open('variables_globales.yaml'))"
          echo "✅ YAML válido"

      - name: Test template generation
        run: |
          cd herramientas/
          python generador.py -t comunicacion/onboarding  # Ejemplo con tu script
