name: Notificaciones
on:
  workflow_run:
    workflows: ["Generación Programada"]
    types: [completed]

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'slack-notification.yml',
              ref: 'main'
            })
