name: Security Scan
on:
  schedule:
    - cron: '0 0 * * *'  # Diario a medianoche
  push:
    paths:
      - '**/requirements.txt'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan dependencies
        uses: ossf/scorecard-action@vV1.2.6
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload results
        uses: github/codeql-action/upload-sarif@vV1.2.6
        with:
          sarif_file: results.sarif
